name: CI Workflow

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # uvのインストール + キャッシュ
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true  # uvのwheelなどはキャッシュOK

      # Pythonのセットアップ
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      # 依存関係インストール
      - name: Install the project
        run: uv sync --all-extras --dev

      # ------- Lintセクション --------
      - name: Lint with Ruff
        continue-on-error: true
        run: uv run ruff check . --output-format=github

      - name: Lint with Mypy
        continue-on-error: true
        run: uv run mypy . --config-file pyproject.toml --ignore-missing-imports --no-namespace-packages

      # ------- Testセクション --------
      - name: Tests with pytest
        run: uv run pytest tests
